---
- hosts: Jenkins-agent
  become: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: install java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Download Maven packages
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
    
    - name: Extract maven packages
      unarchive:
        src: /opt/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
        remote_src: yes
        
    - name: install docker.io
      apt: 
        name: docker.io 
        state: present

    - name: start docker services
      service: 
        name: docker
        state: started


#- name: give 777 permissions on /var/run/docker.sock
