---
- hosts: Jenkins-controller
  become: true
  tasks:
    - name: add jenkins key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
      
    - name: add jenkins repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: install java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: install jenkins
      apt:
        name: jenkins
        state: present

    - name: start jenkins service
      service:
        name: jenkins
        state: started

    - name: enable jenkins service at boot
      service:
        name: jenkins
        enabled: yes
